apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wey1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-wey1@sha256:836721cca5df7e7e5a06c01b189bf7fa042609d80541630300e6608e5cc5474b
        name: my-nodejs
        resources: {}
status: {}
